version: '3'

services:
  elasticsearch:
    image: ${ES_OSS_IMAGE}
    hostname: elasticsearch
    container_name: elasticsearch
    networks:
      - elasticsearch
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    command: ${ES_COMMAND}
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  xpack:
    image: ${ES_IMAGE}
    hostname: elasticsearch-xpack
    container_name: elasticsearch-xpack
    environment:
      - cluster.name=xpack
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.watcher.enabled=true
      - http.port=9210
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=elastic
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9210:9210
  opendistro: # or opensearch
    image: ${ES_OPENDISTRO_IMAGE:-rwgrim/docker-noop}
    hostname: elasticsearch-opendistro
    container_name: elasticsearch-opendistro
    environment:
      - cluster.name=opendistro
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - opendistro_security.ssl.http.enabled=false
      - http.port=9220
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9220:9220
  kibana:
    image: ${ES_KIBANA_IMAGE:-rwgrim/docker-noop}
    hostname: elasticsearch-kibana
    container_name: elasticsearch-kibana
    networks:
      - elasticsearch
    environment:
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: aaaa1111bbbb2222cccc3333dddd4444
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
networks:
  elasticsearch:
    driver: bridge
